version: '3'

services:

  wlp:
    image: lt:5000/welcome-local-page:latest
    ports:
      - "4000:3000"
    # volumes:
    #   - app-config/wlp-config.yml:/app/wlp-config.yml
    environment:
      RAILS_ENV: development
