services:

  wlp:
    image: lt:5000/welcome-local-page:latest
    restart: always
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER:-wlp}:${POSTGRES_PASSWORD:-wlp}@db:5432/${POSTGRES_DB:-wlp}
      WLP_CONFIG_PATH: /app/app-config/wlp-config.yml
