version: '3'

services:
  app:
    image: lt:5000/welcome-local-page:latest
    ports:
      - "3000:3000"
    volumes:
      - wlp-config.yml:/app/wlp-config.yml
    env_file: .env
    environment:
      RAILS_ENV: development
