welcome-text: "Welcome local page"
resources:
  - name: "Grafana"
    server_name: "lt" 
    url: "http://lt:3000"
    image: ''
  - name: "Gitea"
    server_name: "lt" 
    url: "http://lt:3030"
    image: ''
  - name: "Jellyfin"
    server_name: "lt"
    url: "http://lt:8096"
    image: ''
  - name: "qbitorrent"
    server_name: "lt"
    url: "http://lt:8097"
    image: ''
  - name: "dashdot"
    server_name: "lt"
    url: "http://lt:3002"
    image: ''
  - name: "Uptime Kuma"
    server_name: "lt"
    url: "http://lt:3001"
    image: ''
  - name: "Portainer"
    server_name: "lt"
    url: "http://lt:9000"
    image: ''
  - name: "Dozzle"
    server_name: "lt"
    url: "http://lt:8889/"
    image: ''
  - name: "SNMP Browser"
    server_name: "lt"
    url: "http://lt:7000"
    image: ''
  - name: "Immich"
    server_name: "lt"
    url: "http://lt:2283"
    image: ''
  - name: "n8n"
    server_name: "lt"
    url: "http://lt:5678"
    image: ''
  - name: "moodies gallery"
    server_name: "lt"
    url: "http://lt:13000"
    image: ''
  - name: "Temporal"
    server_name: "lt"
    url: "http://lt:48080"
    image: ''
  - name: "Dokploy"
    server_name: "lt"
    url: "http://lt:3003"
    image: ''
  - name: "Invest Portfolio Analyzer"
    server_name: "lt"
    url: "http://lt:8080"
    image: ''
  - name: "Jaeger"
    server_name: "lt"
    url: "http://lt:16686"
    image: ''